package base.model;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.github.javafaker.Faker;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.Random;

import static utils.ModelsUtils.getRandomValueForTransactionType;

/**
 * Transaction POJO
 *
 * This class contains all attributes from deserialization Accounts from API
 * @Author Daniel.Jaramillo01
 */
@JsonDeserialize
public class Transaction {

    /**
     * Account elements
     */
    private String firstName;
    private String lastName;
    private String accountNumber;
    private String transactionType;
    private String email;
    private boolean active;
    private String country;
    private String telephone;
    private double amount;
    private int id;

    private static List<Transaction> transactions = new ArrayList<>();
    private static final Faker faker = new Faker();

    public Transaction() {
        firstName = faker.name().firstName();
        lastName = faker.name().lastName();
        accountNumber = faker.idNumber().valid();
        transactionType = getRandomValueForTransactionType();
        email = faker.internet().emailAddress();
        isEmailUnique();
        active = faker.bool().bool();
        country = faker.country().name();
        telephone = faker.phoneNumber().phoneNumber();
        amount = 0 + new Random().nextFloat() * 100000;
        transactions.add(this);
    }

    public static void cleanListOfTransactions() {
        transactions = new ArrayList<>();
    }

    /**
     * This method validates that other transactions on list don't have the same email generated by faker
     *
     * @Author Daniel.Jaramillo01
     */
    private void isEmailUnique() {
        boolean isNotUnique = true;
        do {
            if (transactions.stream().anyMatch(t -> Objects.equals(t.email, email))) {
                System.out.println("not unique");
                email = faker.internet().emailAddress();
            } else {
                isNotUnique = false;
            }
        } while (isNotUnique);
    }

    public static List<Transaction> getTransactions() {
        return transactions;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getAccountNumber() {
        return accountNumber;
    }

    public void setAccountNumber(String accountNumber) {
        this.accountNumber = accountNumber;
    }

    public String getTransactionType() {
        return transactionType;
    }

    public void setTransactionType(String transactionType) {
        this.transactionType = transactionType;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public boolean isActive() {
        return active;
    }

    public void setActive(boolean active) {
        this.active = active;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public String getTelephone() {
        return telephone;
    }

    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    public double getAmount() {
        return amount;
    }

    public void setAmount(double amount) {
        this.amount = amount;
    }

    public int getId() {
        return id;
    }
}
